export class Item {
  ITEM_ID!: string; // Unique ID (auto-generated by database)
  ITEM_NAME_EN!: string; // Item name in English
  ITEM_NAME_AR!: string; // Item name in Arabic
  ITEM_PRICE!: number; // Item price (number)
  DESCRIPTION_EN!: string; // Description in English
  DESCRIPTION_AR!: string; // Description in Arabic
  CATEGORY_NAME_EN!: string; // Category name in English
  CATEGORY_NAME_AR!: string; // Category name in Arabic
  CATEGORY_ICON!: string; // URL or base64 for category icon
  ITEM_PHOTO!: string; // URL or base64 for item photo
  OFFER?: number; // Offer/discount (optional)
  ADMIN_ID!: string; // Admin who created/edited the item
  IS_PUBLISHED!: boolean; // Is the item published/active
  TIMESTAMP_CREATED!: number; // Unix timestamp
  ITEM_SIZES?: { [size: string]: number }; // Optional: sizes and prices
  OWNER_ID!: number; // Owner/branch ID
  TYPE!: string; // "restaurant" or other type
}

